# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ClassRoom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ClassRoom
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  # target 'ClassRoom-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'ClassRoomTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'ClassRoom-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for ClassRoom-tvOS

#   target 'ClassRoom-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
